name: Repo Sync

on:
  schedule: 
  - cron: "*/2 * * * *" # every 2 minutes. set to whatever interval you like

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: deepcharles/assign-test-1
        source_branch: main
        destination_branch: repo-sync
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: repo-sync
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}